FROM continuumio/miniconda3

SHELL ["/bin/bash", "-c"]

RUN chmod -R 777 /home && \
    mkdir /home/build && \
    mkdir /opt/node_app

RUN apt-get update && \
    apt-get install -y docker.io gcc

RUN pip install --upgrade pip && \
    pip install crawl4ai[sync] && \
    pip install beautifulsoup4

RUN apt-get install -y nodejs npm && \
    cd /opt/node_app && \
    npm install puppeteer && \
    npx puppeteer install && \
    apt-get install -y libx11-dev libx11-xcb-dev libxcomposite-dev libxcursor-dev \
                       libxdamage-dev libxi-dev libxtst-dev libnss3-dev libcups2-dev \
                       libxss-dev libxt-dev libxrandr-dev libasound2-dev libatk1.0-dev \
                       libpangocairo-1.0-0 libgtk-3-dev libgbm-dev

RUN playwright install

ENTRYPOINT ["/bin/bash"]

WORKDIR /home