# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Xinchen Wang 王欣辰

import subprocess
import os, sys
import re
import enum
import difflib
import os
import json
import requests
import time
from pathlib import Path
import tempfile
from itertools import groupby
from enum import Enum
import base64
import argparse
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)
from utils.tools_config import Tools
TIME_OUT_LABEL= ' seconds. Partial output:'
DIFF_FENCE = ["```diff", "```"]
BASH_FENCE = ["```bash", "```"]
HEAD = "<<<<<<< SEARCH"
DIVIDER = "======="
UPDATED = ">>>>>>> REPLACE"

INIT_PROMPT = f"""
<IN GOOD FORMAT> 
All your answer must contain Thought and Action. 
Calling CLI tools Action using bash block like {BASH_FENCE[0]}  {BASH_FENCE[1]}. 
Editing and Writing code Action using diff block like {DIFF_FENCE[0]} {DIFF_FENCE[1]}.
The command line you generate will be run in the bash sandbox environment, and the running results will be returned to you through the system messages.

IMPORTANT TIPS: 
    * Each round of reply can only contain one {BASH_FENCE[0]} {BASH_FENCE[1]} block or one {DIFF_FENCE[0]} {DIFF_FENCE[1]} block, which means Each round of your answers contain only *ONE* action!
    * Please submit the first command first, then after receiving the response, you can issue the second command. You are free to use any other bash communication.
</IN GOOD FORMAT> 
"""

EDIT_PROMPT = f"""
<Edit Commands>
CODE EDITING AND WRITING: All changes to files must use the {DIFF_FENCE[0]}  {DIFF_FENCE[1]}  block format, with symbols {HEAD}, {DIVIDER} and {UPDATED}
You need to provide code patch. The patch should according to the original code, indent correctly, and do not include line numbers. The format is as follows: 
### Thought: Modify explanation...
### Action: 
{DIFF_FENCE[0]} 
/absolute/path/of/target.py
{HEAD}
    exact copy of old line(s) you would like to change
{DIVIDER}
    new line(s) to replace
{UPDATED}

{HEAD}
    exact copy of old line(s) you would like to change
{DIVIDER}
    new line(s) to replace
{UPDATED}
{DIFF_FENCE[1]} 
Every *SEARCH/REPLACE block must use this format:
1. The opening fence {DIFF_FENCE[0]} 
2. The file path alone on a line, verbatim. No bold asterisks, no quotes around it, no escaping of characters, etc.
3. The start of search block: {HEAD}
4. A contiguous chunk of lines to search for in the existing source code
5. The dividing line: {DIVIDER}
6. The lines to replace into the source code
7. The end of the replace block: {UPDATED}
8. The closing fence: {DIFF_FENCE[1]} 
Once you want to modify the code you MUST: 
        * Include *ALL* the code being searched and replaced!
        * Every *SEARCH* section must *EXACTLY MATCH* the existing source code, character for character, including all comments, docstrings, etc.
        * '{HEAD}', '{DIVIDER}' and  '{UPDATED}' symbols must be on a line by themselves and cannot be indented.
        * All code modifications must be expressed in the REPLACE format above (including delete an insert). We will find the source code with the highest matching degree in the original file and replace it. Please provide sufficient and unique old line(s) from snippet to facilitate matching.
        * If the code patch you provide is successfully applied, the differences before and after the code modification will be returned.
        * The paths of modified files must be completely absolute paths.
        * Make sure the patch you provide is indented correctly especially in python programs: The indentation of old lines is exactly the same as the original code, and the indentation of new lines is correct.
        * All patches must be based on the original code viewed by the tools, and fabricated code patch(es) is prohibited.
        * Previously successfully applied patches will modify the code, and new patches must be applied based on the current code. Please review the relevant code again then provide new patches.
        * If the old line(s) is empty, it is considered to be inserted at the beginning of the file. If the file does not exist, a new file will be created and the new line will be written. like:
### Thought: Create a.py
### Action:
{DIFF_FENCE[0]}
/project_path/.../a.py
{HEAD}
{DIVIDER}
    [new line(s) to add]
{UPDATED}
{DIFF_FENCE[1]}
</Edit Commands>
"""

REPORT_PROMPT = """
As an expert in code generation tasks, your task is to carefully evaluate the responses generated by Large Language Models based on given code generation task.

<Workflow>
1. Carefully read the code generation task and the response generated by the Large Language Models.
2. Carefully read the task requirements and stepwise evaluation results analyzed by your collaborators.
3. Score the LLM-generated response based on four dimensions: Correctness, Completeness, Relevance, and Clarity, and provide an overall score.
4. Provide the reasoning for your scores based on your evaluation.
</Workflow>

<Important Tips>
- You need to discern carefully about the stepwise evaluation results, as they may contain inaccuracies or invalid evaluations!
- Focus on whether the response meets the task requirements and fulfills the user's needs, rather than being overly critical of minor issues.
- When the LLM's response has only minor issues (such as code style problems, slight performance issues, lack of error handling, lack of text comments, etc.) that do not affect the realization of the user's needs, give a relatively high score.
- When the LLM's response has fundamental functional defects, contains critical logical errors and syntax errors, or is extremely difficult to read, give a relatively low score.
</Important Tips>

<Evaluation Criteria>
1. **Accuracy**: How accurate are the model's answers in terms of factual correctness? Do they contain any errors or misleading information?  
    - **Guidelines**:  
        - Carefully review the model's answers to identify any potential errors or misleading information.  
        - Verify the factual correctness of the answers to ensure there are no mistakes or misleading details.  
        - Ensure that any cited sources or data are indisputably correct.  
    - **Scoring**:  
        - **0**: Mostly incorrect or misleading; contains numerous and significant factual errors.  
        - **1**: Significant factual errors, partially accurate; more than half of the information is incorrect.  
        - **2**: Some factual errors, but mostly accurate; contains several minor mistakes.  
        - **3**: Slight inaccuracies, but overall correct; includes a few small errors.  
        - **4**: No errors, completely accurate; all information is factually correct.  

2. **Completeness**: Does the model's answer cover all aspects of the user's question, or does it omit any key points?  
    - **Guidelines**:  
        - Read the user's question to identify all key components that should be included in the answer.  
        - Carefully review the model's answer to identify any missing key points.  
        - Ensure no key points are omitted, and the explanation is not overly brief.  
    - **Scoring**:  
        - **0**: Mostly incomplete, omits many key points; lacks most critical aspects.  
        - **1**: Significant omissions, partially complete; misses more than half of the key points.  
        - **2**: Some omissions, but covers most key points; misses a few critical aspects.  
        - **3**: Slight omissions, but mostly complete; misses one or two minor points.  
        - **4**: Fully comprehensive, no omissions; thoroughly covers all key aspects.  

3. **Relevance**: Does the model's answer accurately address the core concerns of the question?  
    - **Guidelines**:  
        - Carefully read the user's question to understand the core concerns and requirements.  
        - Compare the model's answer to the user's question to determine if it directly addresses the core concerns without going off-topic.  
        - Ensure the answer does not deviate from the topic, include irrelevant information, or omit any important relevant details.  
    - **Scoring**:  
        - **0**: Mostly irrelevant or off-topic; does not address the core concerns.  
        - **1**: Contains significant irrelevant information, partially relevant; addresses less than half of the core concerns.  
        - **2**: Some irrelevant information, but mostly relevant; addresses most core concerns but includes unrelated details.  
        - **3**: Mostly relevant, with slight irrelevant information; nearly addresses all core concerns.  
        - **4**: Directly addresses all core concerns, no irrelevant information; fully relevant to the question.  

4. **Clarity**: Is the model's answer explained in an easy-to-understand manner, with clear logic and no ambiguity?  
    - **Guidelines**:  
        - Read the model's answer to assess its logical clarity and conciseness.  
        - Check if the answer is easy to understand, with no vague or ambiguous parts.  
        - Ensure the answer is organized in a logical and coherent sequence.  
    - **Scoring**:  
        - **0**: Mostly unclear or confusing; very difficult to understand.  
        - **1**: Significant ambiguity, partially understandable; contains several confusing parts.  
        - **2**: Some ambiguity, but mostly understandable; includes a few unclear sections.  
        - **3**: Mostly clear, with slight ambiguity; generally easy to understand, with minor issues.  
        - **4**: Very clear, no ambiguity, well-organized; completely easy to understand.  

5. **Overall Score**:  
    - **Guidelines**:  
        - Based on the scores from the four dimensions above, provide an overall score from 0 to 4.  
    - **Scoring**:  
        - **0**: Performs extremely poorly in all or most dimensions. The answer is almost entirely incorrect, incomplete, irrelevant, and unclear.  
        - **1**: Performs poorly in most dimensions. The answer contains significant errors or omissions, is partially relevant but overall unclear.  
        - **2**: Performs moderately in some dimensions. The answer has some errors or omissions, is mostly relevant, and relatively clear.  
        - **3**: Performs well in most dimensions. The answer is mostly correct, complete, and relevant, with only minor errors or clarity issues.  
        - **4**: Performs excellently in all dimensions. The answer is completely correct, comprehensive, relevant, and clear.  
</Evaluation Criteria>

<Report Format>
If you ensure that you have evaluated the answer from all possible aspects, please submit the report in the following format:
### Final Report:
Correctness Score: {Correctness Score}
Evaluation Reason: {evaluation_reason}

Completeness Score: {Completeness Score} 
Evaluation Reason: {evaluation_reason}

Relevance Score: {Relevance Score} 
Evaluation Reason: {evaluation_reason}

Clarity Score: {Clarity Score} 
Evaluation Reason: {evaluation_reason}

Overall Score: {Overall Score}
Overall Evaluation Reason: {overall evaluation_reason}
</Report Format>
"""

COMPREHENDER_PROMPT = "Your colleagues have identified the overall requirements of the code generation task and broken down the specific requirements."

BUILD_PROMPT = "Your colleagues have configured the complete environments according to the code generation task and you do not have to build the environment again."

COMPREHENDER_REPORT = """
# Task Requirements
**Overall Task Requirements**: {overall task requirement}
**Specific Task Requirements**:
    {specific task requirement 1}
    {specific task requirement 2}
    {specific task requirement X}
"""

BUILD_REPORT = """
# Environment Configuration
    **Step 1**   {Command 1}   {Explanation 1}
    **Step 2**   {Command 2}   {Explanation 2}
    **Step 3**   {Command 3}   {Explanation X}
"""

SINGLE_SETP_REPORT = f"""
(When reporting the evaluation result of a single step, please strictly follow the format below. The evaluation results should be professional and clear, avoiding lengthy, repetitive, and irrelevant evaluation information.
Besides, text or table HTML tags should be enclosed in backticks. For example, `<div>` should be `<div>`. Ensure that all code blocks use the correct syntax highlighting.):

## Step X: (Dynamic Execution / Static Linter / Unit Tests / Screenshot / Interaction / Web Browsing / General Semantic / Bash Command)
**Step Description**: In this step, the (Static Linter / Dynamic Execution / ...) is invoked to evaluate (a specific part) of the response.

(If it is a Dynamic Execution Analysis, please follow the format below:)
**Dynamic Execution Analysis**: {{analysis}}
**Execution Command**: {{execution command}}
**Execution Messages**: {{execution message}}

(If it is a Static Linter Analysis, please follow the format below:)
**Static Linter Analysis Overview**: {{analysis}}
**Detailed Static Linter Analysis**:

| Linter Tool | Linter Analysis Type | Linter Analysis Message |
|-------------|----------------------|-------------------------|
| Tool Name   | Type (Error/Warning/Success/Other) | Detailed Linter Analysis Message |

(If it is a Unit Test Analysis, please follow the format below:)
**Unit Test Analysis**: {{analysis}}
**Execution Command**: {{execution command}}
**Execution Messages**: {{execution message}}

(If it is a Screenshot Analysis, please follow the format below:)
**Screenshot Analysis**: {{analysis}}
**Screenshot**: ![Screenshot](absolute path of the screenshot)

(If it is a Interaction Analysis, please follow the format below. Note: Replace "absolute path of the screenshot" with the actual path to the screenshot.)
**Interaction Analysis**: {{analysis}}
**Interaction Content**: ![Screenshot](absolute path of the screenshot)

(If it is a Web Browsing Analysis, please follow the format below.)
**Web Browsing Analysis**: {{analysis}}
**Web Browsing Content**: {{web browsing content}}

(If it is a General Semantic Analysis, please follow the format below:)
**General Semantic Analysis**: {{analysis}}

(If it is Bash Command, please follow the format below:)
**Command Analysis**: {{analysis}}
"""
    

SINGLE_STEP_PROMPT = """
- You can only execute a single step based on the evaluation plan or report the evaluation result of the single step per round!
- If you want to report the evaluation result of the single step in this round, please resubmit your single step report and use the action `report_single_step'. Follow the format below:
### Thought:
I will report the evaluation result of the current step in the plan.
### Action:
```bash
report_single_step
```
### State: Analyse
### Single Step Report:       
XXX 
"""

REPORT_PROMPT_COMPETE = """
As an expert in evaluating code generation tasks, your mission is to carefully assess the LLM-generated response for a given code generation task.
Now that both you and your collaborators have provided scores, you need to engage in mutual negotiation and discussion to ensure consistency and professionalism in the evaluation scores.
In each round of discussion, you can take one or more of the following actions:

1. Maintain <explanation>: Maintain your current score and provide an explanation.
Example:
### Thought: My score is already accurate and does not need to be changed.
### Action: Maintain "My score is already accurate and does not need to be changed because..."

2. Change <overall_score> <explanation>: Adjust your own overall score and provide a detailed explanation for the new score. Carefully consider your collaborators' feedback before deciding whether to change your score.
Example:
### Thought: Considering the feedback from other collaborators, I have decided to adjust my score to 3.
### Action: Change 3 "Considering the feedback from other collaborators and their valid concerns about code readability, I have decided to adjust my score to 3 because..."

3. Agree <judge_id> <explanation>: Explicitly agree with another judge's score and reason, and provide an explanation.
Example:
### Thought: I agree with the second collaborator's score because their reasoning about code efficiency is valid.
### Action: Agree 2 "I agree with the second collaborator's score because their reasoning about code efficiency is valid."

4. Query <judge_id> <explanation>: Request clarification or further justification from another judge regarding their score or reasoning. This is a moderate form of discussion, focusing on seeking more information or explanation.
Example:
### Thought: I would like more details on why the first collaborator gave a lower score.
### Action: Query 1 "Could you clarify the specific issues that led to your lower score?"

5. Disagree <judge_id> <explanation>: Explicitly express disagreement with another judge's score and reason, and provide a clear explanation. This is a stronger form of discussion than Query, directly challenging the other judge's assessment.
Example:
### Thought: I disagree with the third collaborator's score because it overlooks critical logical errors in the code.
### Action: Disagree 3 "I disagree with the third collaborator's score because it overlooks critical logical errors in the code."

6. Withdraw <round_id> <explanation>: Withdraw a previous negotiation action (Agree, Query, or Disagree) from a specific round. Clearly state which action you are withdrawing, the round in which it occurred, and the reason for the withdrawal.
Example:
#### Thought: Upon further reflection, I realize my previous disagreement in round 2 was not justified.
#### Action: Withdraw 2 "In round 2, I took a Disagree action, which I now wish to withdraw because the collaborator has changed the score"

Here's an example of how to take multiple actions in one round of discussion (each action should have a separate ### Action):

### Thought:
My original score for the code's correctness is accurate, so I will maintain it. However, I noticed that another collaborator's score does not account for the lack of comments in the code, so I will question their score.
### Action:
Maintain "My score for correctness is already accurate and does not need to be changed because the code produces the correct output for all test cases provided."
### Action:
Query 2 "The other collaborator's score overlooks the lack of comments and documentation, which impacts code readability and maintainability."

<Important Tips>
- The <judge_id> in the `Agree`, `Query`, and `Disagree` actions must be an integer!
- The <overall_score> in the `Change` action must be a float!
- The <round_id> in the `Withdraw` action must be an integer!
- Only use Query or Disagree when your collaborator's overall score is different from yours!
- You need to carefully discern the stepwise evaluation results, as they may contain inaccuracies or invalid evaluations!
</Important Tips>
"""

REASON_PROMPT = """
As an expert in evaluating code generation tasks, your mission is to generate the Overall Evaluation Results for a given code generation task and the LLM-generated response. You need to synthesize all collaborators' evaluation reasons and provide optimization suggestions.

## FINAL REPORT: Please submit the Overall Evaluation Results in the following format:

# Overall Evaluation Results
**Evaluation Reason**: {evaluation reason}
**Optimization Suggestion**: {suggestions}
"""

def extract_actions(text):
    return text.count('### Action:')

def extract_commands(text):
    if '### Action:' not in text:
        return None
    pattern = rf'{BASH_FENCE[0]}([\s\S]*?){BASH_FENCE[1]}'
    matches = re.findall(pattern, text)
    command_text = ''
    if len(matches) > 0:
        command_text = matches[0]

    commands = []
    if command_text:
        commands = list(filter(None, command_text.split('\n')))
    return commands

def extract_report(text):
    if "### Final Report:" in text:
        return text.split('### Final Report:')[-1]
    else:
        return None
    
def extract_single_step(text):
    single_step_report = None
    state_execute = None
    state_report = None

    if "### Single Step Report:" in text:
        single_step_report =  text.split('### Single Step Report:')[-1].strip()
    state_execute = text.count('State: Execute')
    state_report = text.count('State: Analyse')
    return single_step_report, state_execute, state_report

    
def append_trajectory(trajectory, messages, agent: str):
    for message in messages:
        message['agent'] = agent.lower()
        trajectory.append(message)

def save_trajectory(id, traj_dir, trajectory):
    trial_index = 1
    def get_unique_filename(traj_dir, trial_index):
        filename = f"{id}_{trial_index}.txt"
        while os.path.exists(os.path.join(traj_dir, filename)):
            trial_index += 1
            filename = f"{id}_{trial_index}.txt"
        return filename
    
    traj_file = get_unique_filename(traj_dir, trial_index)
    trajectory_json = json.dumps(trajectory, indent=4, sort_keys=True, ensure_ascii=False)
    with open(os.path.join(traj_dir, traj_file), 'a', encoding='utf-8') as file:
        file.write(f"{trajectory_json}\n")

def generate_report(item, final_score, comprehend_report, build_report, specialized_report, overall_report):
    final_report = f"""
# Code Task
{item['query']}

# LLM-generated Response
{item['answer']}

# Evaluation Score
overall score: {final_score}

{build_report}

{comprehend_report}

{specialized_report}

{overall_report}
"""
    return final_report

def save_report(id, container_name, report_path, report, images_path):
    trial_index = 1

    def get_unique_filename(folder_path, trial_index):
        filename = f"{id}_{trial_index}.md"
        while os.path.exists(os.path.join(folder_path, filename)):
            trial_index += 1
            filename = f"{id}_{trial_index}.md"
        return filename

    folder_path = os.path.join(report_path, str(id))
    os.makedirs(folder_path, exist_ok=True)

    report_file = get_unique_filename(folder_path, trial_index)
    write_path = os.path.join(folder_path, report_file)

    with open(write_path, 'w') as file:
        file.write(report)

    if images_path:
        for image_path in images_path:
            command = f"docker cp {container_name}:{image_path} {folder_path}"
            subprocess.run(command, capture_output=True, text=True, shell=True)

    return write_path

def save_score(id, score_path, raw_score, agent_score, raw_intent, agent_intent):

    item = {'id': id, 'raw_score': raw_score, 'agent_score': agent_score, 'raw_intent': raw_intent, 'agent_intent': agent_intent}
    with open(os.path.join(score_path, 'score.jsonl'), 'a', encoding='utf-8') as file:
        file.write(json.dumps(item, ensure_ascii=False) + '\n')

def extract_diffs(text):
    if '### Action:' not in text:
        return None
    pattern = rf'{DIFF_FENCE[0]}([\s\S]*?){DIFF_FENCE[1]}'
    matches = re.findall(pattern, text)
    diffs = ''
    if len(matches) > 0:
        diffs = '\n'.join(matches)
    return diffs

def save_diff_description(text):
    temp_dir = "/tmp/patch"
    os.makedirs(temp_dir, exist_ok=True)
    cmd = f"sudo chmod -R 777 {temp_dir}"
    subprocess.run(cmd, check=True, shell=True)
    with tempfile.NamedTemporaryFile(mode='w+', dir=temp_dir, delete=False) as temp_file:
        temp_file_path = temp_file.name
        os.chmod(temp_file_path, 0o777)
        temp_file.write(text)
    return temp_file_path

def action_check(evaluater_answer, plan_list = None, role = None):
    final_report = extract_report(evaluater_answer)
    single_step_report, state_execute, state_report = extract_single_step(evaluater_answer)
    commands = extract_commands(evaluater_answer)
    diffs = extract_diffs(evaluater_answer)
    actions = extract_actions(evaluater_answer)
    system_res = ''
    flag = True

    if final_report and actions:
        flag = False
        system_res += "### Observation: \nERROR! Your reply contains both the final report and intermediate action, which is not acceptable. Please submit the final report only after you have completed your tasks."

    if commands and diffs:
        flag = False
        system_res += f"### Observation: \nERROR! Your reply contains both bash block and diff block, which is not acceptable. Each round of your reply can only contain one {BASH_FENCE[0]} {BASH_FENCE[1]} block or one {DIFF_FENCE[0]} {DIFF_FENCE[1]} block. Each round of your answers contain only *ONE* action!"

    if not final_report and not actions:
        flag = False
        system_res += "### Observation: \nERROR! Your reply does not contain valid bash or diff block or final report."
    
    if diffs:
        if HEAD not in diffs or DIVIDER not in diffs or UPDATED not in diffs:
            flag = False
            system_res += f"""### Observation: \nERROR! Your patch is incomplete with {HEAD} or {DIVIDER} or {UPDATED} missing!           
The edit format is as follows: 

{DIFF_FENCE[0]} 
/absolute/path/of/target.py
{HEAD}
    exact copy of old line(s) you would like to change
{DIVIDER}
    new line(s) to replace
{UPDATED}
"""

    if commands:
        if len(commands) > 1:
            if commands[0].split(' ')[0] in ['vim', 'vi', 'echo', 'cat', 'nano', 'sed', 'awk']:
                flag = False
                system_res += f"""### Observation: \nERROR! If you want to edit files, all changes to files must use the {DIFF_FENCE[0]}  {DIFF_FENCE[1]}  block format, with symbols {HEAD}, {DIVIDER} and {UPDATED}.
The edit format is as follows: 

{DIFF_FENCE[0]} 
/absolute/path/of/target.py
{HEAD}
    exact copy of old line(s) you would like to change
{DIVIDER}
    new line(s) to replace
{UPDATED}
""" 

    if role:
        if final_report:
            flag = True
        else:
            total_plan = [json.dumps(step, ensure_ascii=False) for step in plan_list]
            if actions > 1:
                flag = False
                system_res += f"""### Observation: \nERROR! Your reply contains multiple actions, which is not acceptable.
{SINGLE_STEP_PROMPT}
"""     
            if flag and state_execute:
                system_res += "### Observation: \nOnce you have completed the current step, you should report the results in the next round. If the step is not yet finished, please continue working on it.\n"
                
            if flag and state_report:
                system_res += "### Observation: \nYou have submitted the evaluation report of this step. Please review the evaluation steps you have already completed and proceed to the next step. You may take additional steps beyond the given evaluation plan or skip certain steps in the plan based on the actual situation.\n"

    if not flag:
        return None, None, None, None, system_res
    else:
        return final_report, single_step_report, commands, diffs, system_res

def execute_markdown_lint(write_path):
    command = f"prettier --write {write_path}"
    result = subprocess.run(command, capture_output=True, text=True, shell=True)
    print('prettier result:', result)
    return result.stdout

def execute_generate_pdf(write_path):
    output_file = "evaluation_report.pdf"
    pdf_engine = "xelatex"
    cjk_font = "Noto Sans CJK SC"
    geometry = "margin=0.5in"
    header_includes = r"\usepackage{setspace}\setstretch{0.9}"

    command = [
        "pandoc",
        write_path,
        "-o", output_file,
        "--pdf-engine", pdf_engine,
        "-V", f"CJKmainfont={cjk_font}",
        "-V", geometry,
        "-V", f"header-includes={header_includes}"
    ]

    work_dir = os.path.dirname(write_path)

    try:
        subprocess.run(command, check=True, cwd=work_dir)
        print(f"PDF generated: {output_file}")
    except subprocess.CalledProcessError as e:
        print(f"Error occurred: {e}")

def command_check(command, container_name):

    def remove_quotes(arg):
        return arg.strip().strip('\'"')
    
    if 'syntax_check' in command:
        if '-f' not in command.split():
            output_info = f"""Error! Please pay attention to the correct format of the command: 
{Tools.syntax_check.value['command']} # {Tools.syntax_check.value['description']}
"""
            return False, output_info, ''
        else:
            arg = remove_quotes(command.split('-f')[-1].strip())
            command = f"python3 /home/tools/syntax_check.py -f {arg} -c {container_name}" 

    elif 'web_browse' in command:
        if '-q' not in command.split():
            output_info = f"""Error! Please pay attention to the correct format of the command:
{Tools.web_browse.value['command']} # {Tools.web_browse.value['description']}
"""
            return False, output_info, ''
        else:
            arg = remove_quotes(command.split('-q')[-1].strip())
            command = f'python3 /home/tools/web_browse.py -q "{arg}"'

    elif 'screenshot_analyse' in command:
        if '-f' not in command.split():
            output_info = f"""Error! Please pay attention to the correct format of the command: 
{Tools.screenshot_analyse.value['command']} # {Tools.screenshot_analyse.value['description']}
"""
            return False, output_info, ''
        else:
            arg1 = remove_quotes(command.split('-f')[-1].split('-q')[0].strip())
            if arg1.split('.')[-1] != 'html':
                output_info = f"""Error! The file path in the command should be an HTML file: 
{Tools.screenshot_analyse.value['command']} # {Tools.screenshot_analyse.value['description']}
"""
                return False, output_info, ''
            else:
                has_q = '-q' in command.split()
                has_a = '-a' in command.split()
                base_command = f"python3 /home/tools/screenshot_analyse.py -f {arg1}"

                if has_q:
                    arg2 = remove_quotes(command.split('-q')[-1].split('-a')[0].strip())
                    base_command += f' -q "{arg2}"'

                if has_a:
                    arg3 = remove_quotes(command.split('-a')[-1].strip())
                    base_command += f" -a '{arg3}'"

                command = base_command

    return True, '', command